#!/usr/bin/bash

bake_require '../../../playdoh/environments/haskell/Bakefile'

# shellcheck disable=SC2034
SOURCE=main.hs
# shellcheck disable=SC2034
DOCKERCONTEXT="$(pwd)"
# shellcheck disable=SC2034
DOCKERFILE="$(pwd)/Dockerfile"
# shellcheck disable=SC2034
DOCKERIMAGE='ch13:latest'

bake_task build "Builds the project"
function build ()
{
  docker:exec stack build
}

bake_task repl "Loads a GHCI repl"
function repl ()
{
  docker:exec stack ghci "$@"
}

bake_task exec "Runs stack exec"
function exec ()
{
  docker:exec stack exec "$@"
}
