#!/usr/bin/env bash


bake_task init "Initialize the project"
function init ()
{
    docker pull haskell:8.2.1
}

function hrun ()
{
    exec docker run -it --rm --name haskell \
        --workdir /workspace \
        --volume "$(pwd)":/workspace \
        haskell:8.2.1 "$@"
}

bake_task repl "Start a haskell repl"
function repl ()
{
    hrun ghci
}

bake_task shell "Start the environment as a shell"
function shell ()
{
    hrun /bin/bash
}

bake_task compile "Compiles the provided haskell source file"
function compile ()
{
    local filename output
    filename=$(basename $1)
    output="${filename%.*}.out"
    hrun ghc --make -o "$output" "$filename"
}

bake_task clean "Cleans compilation files, leaves the binaries"
function clean ()
{
    rm -rf *.hi *.o
}
