#!/usr/bin/env bash

bake_require '../../../playdoh/environments/haskell/Bakefile'

export COMPOSE_FILE="$PWD/docker-compose.yml"
export DOCKER_IMAGE="haskell:playground"
export DOCKER_NAME="haskell-playground"


bake_task repl "Starts a stack ghci repl"
function repl
{
  compose run haskell stack ghci
}
